
title: [Health Data Analysis Portfolio]
description: [Exploring patient data through R and Python, clustering, and interactive dashboards.
This repository showcases projects in biomedical and clinical data analysis. 
It includes patient clustering, exploratory visualizations, and interactive dashboards built with R (Shiny) and Python. 
The goal is to uncover patterns in clinical outcomes and make complex data easier to explore.]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 