
title: "Health Data Analysis Portfolio"
description: "Exploring patient data through R and Python, clustering, and interactive dashboards."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
