project:
  type: website
  output-dir: docs   

website:
  title: "Healthlytics"
  navbar:
    left:
      - href: README.md
        text: Home
      - text: Projects
        menu:
          - href: https://yurim-nam.github.io/healthlytics/Project_1.html
            text: Schizophrenia PANSS Analysis
