project:
  type: website
  output-dir: docs   

website:
  title: "Healthlytics"
  navbar:
    left:
      - href: https://yurim-nam.github.io/healthlytics/
        text: Home
      - text: Projects
        menu:
          - href: https://yurim-nam.github.io/healthlytics/Project_1.html
            text: Schizophrenia PANSS Analysis

format:
  html:
    theme: default  
    css: styles.css
